name: Build and push image

on:
  push:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fwilhe2
          password: ${{ secrets.DH_PAT }}
      - name: Build and push
        run: docker buildx build --platform=linux/amd64,linux/arm64 --push --tag=fwilhe2/toybox .
